### ISSUE TITLE
Add ability to manually set a field value

### ISSUE THREAD

**Issue by visualfanatic** [BenMagyar/form-hooks#11]
Currently the only way to set a field value is to pass `handleChange` to each fields' `onChange` event callback. It would be great if `useForm` would return along with `handleChange` and the rest something like `setValue` which would take a field name and value:
```js
const { setValue } = useForm({ ... })
setValue('someField', 'test')
```

This could be really helpful for example when you would need to reset a single field and not a whole form.

> EDIT: It could also take a third argument `touched` to inform the internal logic whether the field should be set or not as touched.

**Comment by BenMagyar** [comment]
I think a `setValues` and `setTouched` would work best here in case its multiple fields. This sounds reasonable to me 👍 .

**Comment by BenMagyar** [comment]
Added in 0.7.0, sorry it took me a while ⏩
