### ISSUE TITLE
Add ability to reset a field value

### ISSUE THREAD

**Issue by visualfanatic** [BenMagyar/form-hooks#13]
Similarly to #11 it would be really useful to also have a `resetValue(name)` function that would reset a field to a value from `initialValues`.

EDIT: It could also take a second argument `touched` to inform the internal logic whether the field should be left or not as touched.

**Comment by BenMagyar** [comment]
I think `resetValues(names?: string[])` would make sense here to just reset as many field values as you want. Touched could come through `setTouched` from #11

**Comment by visualfanatic** [comment]
That is even better idea 👍

**Comment by BenMagyar** [comment]
Added in 0.7.0, ended up going with `resetValue(name: keyof Value, shouldResetTouched: boolean = false)` as was originally proposed. Seemed better as I went through it 👍
