### ISSUE TITLE
TypeError: (0 , _react.useState) is not a function

### ISSUE THREAD

**Issue by martinduo** [BenMagyar/form-hooks#6]
I am trying to use your component in my CRA web app. But I immediatly get this:

TypeError: (0 , _react.useState) is not a function
useForm
C:/Users/Bruce/Dropbox/Projects/AcesTrader/node_modules/form-hooks/lib/index.js:117
  114 |     _ref$validateOnChange = _ref.validateOnChange,
  115 |     validateOnChange = _ref$validateOnChange === void 0 ? true : _ref$validateOnChange;
  116 | 
> 117 | var _useState = (0, _react.useState)({}),
      | ^  118 |     _useState2 = _slicedToArray(_useState, 2),
  119 |     errors = _useState2[0],
  120 |     setErrors = _useState2[1];
View compiled
DialogForm
C:/Users/Bruce/Dropbox/Projects/AcesTrader/src/components/Charts/ChartDashboard/DialogForm.js:6
  3 | import React from 'react'
  4 | import { useForm } from 'form-hooks'
  5 | 
> 6 | const DialogForm = () => {
  7 |   const { errors, touched, values, handleBlur, handleChange, handleSubmit, isSubmitting } = useForm({
  8 |     initialValues: {
  9 |       name: 'Bruce',
View compiled
▶ 17 stack frames were collapsed.

My package.json includes these in "dependencies":
    "react": "16.7.0-alpha.0",
    "react-dom": "16.7.0-alpha.0",

I guess it's too early to try this experimental feature.
bruce.martinduo@gmail.com

**Comment by BenMagyar** [comment]
If I had to guess, react/react-dom 16.7.0-alpha.0 aren't installed. I wasn't able to recreate it -- here's a codesandbox example of it working: https://codesandbox.io/s/lxwlrn1o5m

**Comment by BenMagyar** [comment]
Closing, don't think this is an issue 🙈

**Comment by icarter09** [comment]
@BenMagyar I just ran into this same issue and your comment provided the fix. Thanks!

**Comment by wissal92** [comment]
I had the same problem and your answer has fixed it for me. thank u!
